apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: react-rust-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: react-rust-app
  template:
    metadata:
      labels:
        app: react-rust-app
    spec:
      containers:
      - name: my-app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
